---
title: "I miss Miss Lambda"
author: "Lambda Moses"
date: "2023-07-21"
categories: [rant]
---

Or rather, why I don't want you to call me "Dr. Lambda Moses". Yeah, it sounds a bit weird, but I'll explain. 

Technically I'm still Miss Lambda because I'm female and unmarried. Before I graduated, I have seen journals and researchers who don't know me addressing me as "Dr. Moses" in emails, which made me cringe, leading to a reply, "Sorry, I'm not a doctor yet." Now that I have graduated, so I am Dr. Lambda, yet I still cringe. It just feels so weird. I'm not used to it. And no, it's not impostor syndrome, which is common in academia. Rather, I find the continuing existence of the doctor title rather bizarre. "Continuing" because it has changed through time. It used to mean someone who is qualified to teach a subject, but now it has a wider aura of reverence. I don't mean the narrow medical doctors sense; in that case it's somewhat like Senator or Captain in addition to the aura. The problem I have is with the aura that I don't deserve. 

Oh, and why am I thinking and hence writing about this? Well, at both Caltech and UCLA, at least within biology (don't know about other fields and institutions), nobody addresses anyone they already know with their titles (most of the time when I say "Mr.", I'm referring to a dog). We (at least the nice people among us) are all first name basis. Anyone who insists to be called Dr. gets a bad rap as a narcissist, probably because of our general informal vibe and because getting a doctorate is only the baseline. So why am I writing this? Shouldn't it be irrelevant? Because annoyingly, when I fill forms online, whether to sign up for an account to purchase something or access contents or to sign a petition, often the form forces me to put a title, which I never liked because I have no idea why it's relevant. Like shall I put Ms. or Miss? I'm fine either way, but I have somewhat preferred Ms., because why ask women our marital status while not asking men? Now that I've got Dr., the debate intensifies. But why am I debating while some of my colleagues who graduated the same time as I did already put their new degree on their Twitter names? They would probably say, put Dr., nobrainer. Um, how about, uh, Captain? I really like calling myself "Captain Lambda", hence Captain's Log. No, I won't use that on the form, because it's meant to be a joke. In contrast, I can't use "Dr. Lambda" as a joke, or wear the doctoral regalia as a Halloween costume (how did I come up with this idea?), because doing so is disrespectful to Caltech, which I love despite its many faults. It's relevant also because some people are introduced as Dr. something in at least semiformal occasions and I encounter them outside academia and hospitals. They must have their reasons, but don't do that to me and I feel bad about it if you do.

The main reason why I don't like "Dr." is that it violates my egalitarian ideals in most situations. One of the non-academic things I learnt during my PhD is that I have a lot to learn from everyone, not only my colleagues, but also people who aren't as well educated. Within my lab, I learnt leadership and social skills from my advisor Lior and many of my colleagues who are good at organizing lab social events. While Caltech is much less a bubble than UCLA and Westwood due to Caltech's small size, I still find myself somewhat living in a bubble of smart and highly educated people. As a result, I don't feel like getting a PhD is anything special because everyone is doing it or has already done it. So the lifelines of my interactions with the outside world are religion and cycling, where I meet many people outside higher education. I definitely find that it helps to behave like them and talk about what they like, which means I won't talk about my research or even mention that I'm at Caltech, except when the group outside a research setting happens to consist of medical and research professionals so I can nerd out. Below are specific cases where I learnt a lot:

I converted to Islam from atheism back in 2010, though most of my time as a Muslim is heterodox and progressive. Back in 2019, I attended a monthly meeting in a group at the Islamic Center of Southern California (ICSC) called Coffee and Converts. One of the members is a Caucasian woman. While she doesn't seem super smart, I'm really impressed by her compassion and patience. She endured a lot of abuse from her conservative Islamophobic pro-Trump Christian family in the beginning when she converted. I have a similar experience, though my family was atheist rather than Christian. I have long been quite bitter about it and distanced myself from my family and culture (hence my cultural rebel pen name "Lambda Moses") and I could say the vilest things about conservatives, though I forgave them more recently (still, no nations, no borders!). In contrast, she kept on showing love to her family, so eventually her father relented and said that Islam is all about love. While she supports Bernie Sanders, she doesn't have my kind of grudge and shows respect to the other side of the political spectrum. She and her kids have been consistent volunteers for the food pantry to feed homeless people, of which there are too many in LA. In contrast, her Caltech educated husband was said to be an abusive asshole who fails his paternal duty towards his children, though I have only met him once and have never talked to him. She really has a great emotional intelligence that I don't have.

Other examples come from the Pasadena Athletic Association (PAA), my local cycling club. While professionals like doctors and lawyers seem to be over-represented, not every single person is a professional. PAA members tend to be old, and many are way older than I expect from their look. Perhaps cycling makes them youthful, both physically and mentally. This is where I learnt that there is no such thing as too old. I met people in their 60s and 70s who can still ride centuries (100 miles in a day). They are still training to be stronger and faster cyclists. From Strava, I see their discipline and persistence in training. One of them suffered a major injury in a crash 2 to 3 years ago. Through his persistence, he came back even stronger, and rides in the front of the pack. There's another old gentleman who tried to set a world record in the velodrome. While I have only raced once, I know how character building racing can be, because you really need to push through the pain. For me, cycling is actually about curiosity. While I generally have no motivation to exercise, it's the adventure that keeps me riding. Sometimes I think discipline suppresses creativity. Is it true? I don't know. What I know is that my desk is a horrible mess and Einstein's desk is messier than mine. But sometimes I wish that I have a bit more discipline like those people do. Different personality types exist for a reason. I need to do structured workouts and avoid messing up my sleep schedule (well, it's a mess) to make my century adventures more fun because with better fitness, the long trip becomes less physically taxing.

Furthermore, at least in LA, I like the friendly vibe of the cycling community, like we often culturally greet each other on the road even if we don't know each other, and when one cyclist stops by the road, others will stop to offer help even if they don't know each other. I mean by "at least in LA" that because LA is not bike friendly, it takes extraordinary courage and commitment to bike regularly, so when we see other cyclists, it feels like "hey, we have the same mental illness!" When I visited Davis where everyone bikes, nobody bothers with the greeting anymore, just like drivers in LA don't greet each other. Sure, some roadies who ride carbon fiber racing bikes may be snobby towards slower utility cyclists. But I go to different types of cycling events. PAA is mostly roadies riding racing bikes, but I also love CicLAvia and Critical Mass, with many other kinds of cyclists, including fixie culture, bikes with lights and speakers, beach cruisers, lowriders, and etc. From those cultures, I see a lot of creativity, vibrancy, and rebelliousness that college never teaches.

Morals from these examples? To be honest, I certainly don't think my PhD made me a superhero. I don't deserve the reverent aura surrounding the Dr. title. All that I'm doing is to go down a rabbit hole, in a tiny niche of a particular way of thinking about spatial transcriptomics data analysis inspired by neighborhood view geospatial data analysis. Even within spatial data analysis, I'm no expert in geostatistical models (kriging, Gaussian process regression), autoregressive models, and point process analyses. I only know the basics of them. I haven't even derived the mean and variance of good old Moran's I. Within spatial -omics, my way is only one out of many ways of data analysis. I'm no expert in image processing, deep learning, or optimal transport. I have only dabbled in them. I always have too many things that I want to learn but can't because I only have so much time. What a PhD trains me for is to go deep down that rabbit hole and realize how vast it is, i.e. how little of it I have seen. I may go elsewhere in the rabbit hole later. The point is the skills and the process. While the Dr. title signals authority, I certainly don't consider myself an authority in anything other than my little niche, so I would rather not signal authority.

Doesn't everyone have their little niche they are expert in? Also, isn't there so much that schools can't teach? I said that I kind of live in a bubble. While I have been to South LA where educational attainment tends to be lower in my voyages, people who live there are certainly experts and hence authorities in their walks of lives, their oral histories, so I should defer to them on that matter. Most of them most likely have never heard of spatial transcriptomics, so I'm no authority whatsoever. I'm just another visitor. While getting a PhD is not easy, who am I to say that the walks of life in South LA aren't hard, if not harder? If I can have a special title to recognize the hard work to get here, then why don't others who worked even harder get one? An educated elite, effectively a priesthood, paternalistically imposing their actually ignorant point of view has caused so much tyranny. For example, in Boyle Heights, where doctors and nurses recommended Western industrial food and suppressed midwives in order to suppress the healthier Indigenous foodways of Mexican immigrants and impose cultural dominance (from the Indigenous veganism lecture by Claudia Serrato at La Plaza Cocina, January 28, 2023). Corrosion of Indigenous foodways in Mexico led to the prevalence of obesity and type II diabetes, while the Indigenous cactus dishes would help preventing diabetes.

What about the refugees, whose lives are way harder than mine has ever been? I feel bad that I'm privileged enough to be sitting here peacefully writing this rant, while not privileged enough to significantly help the refugees. Many very bright people must have perished on the refugee boats that sank in the Mediterranean and Caribbean seas. Or died from extreme weather without shelter, or dangerous work conditions as they are treated as subhuman just because they were born on the wrong side of the border. However smart they may be, however great they may be if there's no racism, they are denied the opportunities to a PhD. Those who live have to work harder than I have ever worked just to survive. Their work must be recognized, and they must be respected.

One may counter, "You are trained in research skills to create new knowledge, which is the highest level of education, so you deserve to be called a doctor." But I'm not sure why this skill deserves the reverence above many others that are also very valuable. Not that it's not important. We do need people with research skills to understand how the natural and social worlds work and how to solve pressing problems. More generally, we need learned people to reflect and inspire. However, why don't, say, artists and musicians get a special title? The MFA is their terminal degree so they are not doctors, and many of them don't even have degrees. They certainly are important. The R package Voayger was largely written in night shifts accompanied by electronic music of various kind, so I'm hugely indebted to musicians. Making good music isn't easy and takes a lot of training and experiences. What about the chefs? Often I eat out when I don't have time to cook, and because I cook, I know that cooking like a chef is hard because I can't do it. What about actors? What about nurses? Nurses with doctoral degrees (doctor of nursing practice) calling themselves doctors is a [contentious issue](https://www.washingtonpost.com/nation/2023/07/18/doctor-nurse-title-lawsuit-california/) because of laws that only allow medical doctors to call themselves doctors [to avoid patient confusion](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9462903/) (this is another reason why I don't use the Dr. title, but everything I say in this rant means that I agree with the DNP's to be respected for their skills and hard work). What about other care workers? I certainly make a crappy care worker. I admire the girl my parents hired to take care of their cats when they came to visit me for my graduation ceremony, i.e. to watch me officially becoming Dr. Lambda. While my parents said she's not smart, she has great compassion and special skills to take care of cats, although Justia (the cat in my GitHub profile photo) didn't like her. 

It doesn't even have to be skilled labor. Why don't people who are known by their communities to be very kind and just get a special title? Why don't people with a lot of grit and courage get a special title? Those traits can be learnt and practiced and can take years to better develop, right? Aren't people with intellectual disability who try their best to be kind more respectable than smart people using their superior intelligence to do evil? I just feel like it's not fair that I get a special title with an aura of reverence for my special skills while others with different but perhaps equally valuable special characteristics that take just as much effort and dedication don't. Don't they deserve more respect? If I say that everyone who is good in some way needs a special title, and that good is only up to God to judge because we don't know the intentions, then why not just do away with titles and respect everyone? I prefer to be without one. 

Or maybe different but equally respected titles according to occupation? Then how to make sure that the "equally" happens? Like there's Dr. and Rev. and some people are both. It's hard to say which one is more respected. While I absolutely despise priesthood -- those who effectively become gods in place of God, I respect Rev.'s because they don't always do the bad priesthood things. For example, in the Pasadena rent control campaign, some of the core leaders are pastors, so are some of the most enthusiastic supporters when I was canvassing. Many churches want to build affordable housing on their properties but are prevented by zoning laws. Intellectually, some of the people I admire the most are Rev. Dr.'s, such as Alister McGrath and John Polkinghorne. Or maybe making new equal titles is still a bad idea, because people identify with many things other than occupation. Dr. and Rev. are a bit different form Chef and DJ, because the former are not only occupations but also statuses, while the latter are only occupations except among their diehard fans. While Rev. is still more like an occupation but with more of an aura than Chef, an MD who quit practicing is still Dr. The aura because Rev., by definition and in theory (though not in practice such as in the clergy sexual assaults) requires superior moral commitments, while Dr. in general does not besides things like don't plagiarize or falsify data (MD's take the Hippocratic Oath so that's still in theory a moral commitment, but that doesn't apply to all doctoral degrees). The statuses from different walks of life may be difficult to put into a concise word. Furthermore, new statuses may have a hard time to gain respect the existing culturally ingrained ones like Dr. and Rev. have. So I would still prefer no title or things like Comrade, Beloved, Brother, Sister, Mr, Ms, and etc. that applies to everyone of equal status (gender can be a contentious issue, but some people, me included, like our genders, so I have no objection to a feminine title for myself).

Furthermore, why does my rabbit hole skill deserve reverence in and of itself? And I'm going down a rabbit hole in writing this rant. Did I mention the Caltech educated husband who is an abusive asshole? Actually, advisors bullying students and postdocs isn't uncommon due to the power differential. While Lior is a great advisor and a very kind human being, others in my division told horror stories about getting bullied by their advisors. Being a doctor doesn't mean that you are moral. In addition, who designed the weapons of mass destruction? Who built the apparatus of mass surveillance? Who dodges the problems of food apartheid and environmental racism while [shifting the blame to genetics](https://petergelderloos.substack.com/p/thats-not-what-this-machine-is-for)? Who designed the stadiums and highways that displaced poor neighborhoods? And I almost hate myself for this when something I love originated from something I hate: the quantitative revolution in geography originated from the military industrial complex with a culture of toxic masculinity (see [this](https://www.sciencedirect.com/science/article/abs/pii/B9780080449104003138)). This is how dangerous we are when we get brainwashed by the wrong people to become an instrument of tyranny. We can work hard, but in the end be worse than working in vain. We really do need the "other" virtues, of compassion, justice, courage, grit, and etc. We are trained to develop profitable tech, while kept in the dark about social ills because our culture belittles the humanities while it fetishizes science, technology, engineering, and math (STEM), so our tech benefits the capitalist ruling class while we don't rebel against them. Also see [this great article](https://www.commonwealmagazine.org/providentialism-without-god) on the myth of meritocracy and the danger of the "head" belittling the "hand" and the "heart", and [this article](https://blog.pmpress.org/2023/05/14/hospitals-extracting-wealth-from-communities/) on the profitable ills of the healthcare system, which is more about extracting wealth than healthcare.

One may counter, "Just because others don't have it doesn't mean that you can't have yours. Do you feel bad about being housed just because many people aren't?" No, because housing is a human right. It's essential, while using the Dr. title is not. Plus I do indeed feel bad when I waste food while many people are starving, and that's also why I don't like luxuries. While I can use my privileges to help those less privileged, I don't see how using a special title helps, but with some exceptions (see end of the rant).

Anyway, maybe it's just that I miss being a student, so in the past month I tried to do things I used to do in undergrad and earlier in graduate school to feel like a student again. It just feels weird that after being a student for 23 years, I'm suddenly no longer one. I miss being "only" Miss Lambda, and as a result, in additional to my egalitarian ideal, when the form annoyingly forces me to put a title, I would still put Miss or Ms. Being Dr. Lambda feels so old! Well, I still am a student, just not officially, because I always have to learn new things. I'm doing pretty much the same thing as I did in the past 2 years. I still feel like an 18-year-old, as if I don't grow up. Perhaps because I'm not doing the "adult" thing; some of my colleagues are married, and some of them have kids, while I'm still enjoying my blissful single days without family responsibilities, not even thinking about dating as if puberty never came. I also still like potty humor and my nerdy song parody tradition which dates back to high school. I still meow and go crazy when I see cats. Cats can't get enough love! I can still pass as an undergrad, or at least I wish I can. I don't think I can pass as a high school student anymore. 

Are there "postdoc kids"? Back in undergrad, I would be offended if someone called me a kid. But now I want to be a postdoc kid. Maybe that's a sign that I'm old; when I was younger, I always wanted to pretend to be more mature, but now I'm pretending to be more immature, as if I miss the youthful vibrancy but not the authority of parents and teachers. Yes, authority is the reason why I pretended to be more mature. Now, instead, most high school teachers would probably treat me as an authority figure of sorts once they find out that I'm a scientist and doctor (I mean the other kind of doctor), although a junior one and I'm sure that they're much better at teaching than I am. It's all about that aura that I don't deserve. Maybe tenured professors do say "postdoc kids" behind our backs although some of us have kids. Why can't kids have their own kids? After all, when cats have kittens, we still treat the mom cats like kittens. No matter how old cats are, even if they are over 20 years old (like over 100 in human age), we humans will always treat them like kittens. 

I said "the other kind of doctor"; I still wonder what proportion of PhD's in each field think MD's are the _real_ doctors. Most JD's do, because it's frowned upon for lawyers to use the Dr. title and in some places it's illegal. At least to me, while I know that MD's are not superheroes, they still carry a special aura because they directly help patients. While MD's ultimately use our research results so we still matter, I'm not sure how many years if not decades if ever it would take for basic research from spatial -omics to actually save lives, especially given that our unjust political and economic system causes many diseases like type II diabetes, autoimmune diseases, asthma, cancer, and so on say from food apartheid and environmental racism (see the book [Intersectional Environmentalist](https://www.intersectionalenvironmentalist.com/)) and our healthcare system itself is so pathological that better treatment from better understanding of these diseases only available to the privileged (look how Trump was treated when he got covid) is too little and too late, but hugely profitable. Then in this system, among other problems, when patients often delay treatment, fearing medical cost (I'm also tempted to do so), until the illness gets severe, what MD's currently do is also often too little and too late, so we're even. But still, MD's have an edge when they treat the poor out of good faith, so they win, or maybe not, because some of them really profit off rather than help patients and some people go to medical school really for the prestige. However, if we compare the worst of every occupation, then every occupation looks bad. 

We doctors (in both senses) suck because of this system, not that we inherently suck, but that if we aren't complicit in its injustice (some of us are), then we aren't doing better than cleaning up its mess. We don't entirely suck, because some cleaning is better than nothing, and not all diseases are caused by the mess (say Mendelian diseases, wound healing, and so on, but then I don't know how equitably distributed the cool new treatments are -- most likely not equitable so there still is a mess; covid pandemic is caused or at least greatly exacerbated by the mess). In order to not to suck so terribly, I really need to do more than spatial transcriptomics; I need to fight these systemic problems. The sociological things I said just now are already outside my jurisdiction and I'm sure that it's way more complicated so take it with a grain of salt. OK, we don't suck. I don't have to know what use my discoveries will have, which I can't anticipate. Climate scientists have it way worse when governments and corporations are preventing climate actions, but that doesn't mean that climate scientists suck. Also think about the astronomers and paleontologists. 

That said, disliking the Dr. title doesn't mean that I'm ashamed of my PhD as if it's a disease or that I discourage students from pursuing it. I'm offended when quacks call themselves doctors or when there are doctoral degrees in quackery or when some people, yes, at Caltech, somehow get to graduate with crappy theses. Actually, in some cases, using the Dr. title does not violate my egalitarian ideals. I'm not too bothered with journals calling me a doctor, because everyone either is one or is becoming one anyway and it's the default when the senders don't check if one has graduated or not; it merely signifies that I'm a member of this club, no aura implied (play [this song](https://youtu.be/9yhI96-zGFI?t=96)). Another of such cases is when addressing an authority figure (who is not a patient), such as a politician or a professor who doesn't know me (especially a famous one or one in a different field), basically when I don't expect to be taken seriously because I'm in a disempowered position so I need that aura. I would introduce myself as Dr. Lambda to get them to take me more seriously, and I have done so when signing a petition. Well, I said that I'm not an authority outside my little niche, but probably neither is the authority of the authority figure justified. It was said that some BIPOC women insist on using the Dr. title, or they won't be taken seriously because of racism and sexism. When it comes to a professor in another field, maybe saying that I'm trained in research in a different field can make them take me more seriously than if I'm a random person on the street because at least I think before I message so the conversation is more likely to be meaningful. OK, it's just a hypothesis; I don't know if it's true, but I tried it once and I did get taken seriously when I messaged the author of a book outside my field. Or maybe it doesn't work, because the author is an anarchist, which means he also has the egalitarian ideal which compels him to take me seriously, though he used the Dr. title in his profile which caused me to use it as well. This is not a systematic study on whether using the title caused me to be taken more seriously.

Or maybe, when one of my parents gets terminally ill, I may say "Dr. Lambda" just to make him/her happy, because they're proud of me being Dr. Lambda, so I put that aura to good use. Or maybe, because I'm better trained in reading research literature and performing data analysis than the average MD, I can introduce myself as "Dr. Lambda" to the doctor treating my parents to discuss new developments in treating this disease, so they don't see me as just another random relative. I'm sure that I will read the literature and perform in depth data analysis on the disease my parents or myself get (if I'm not too sick to do research) and talk to researchers in the field, maybe in the same hospital. Or, like, "Uh, h...hi Dr. X, I'm Dr. Lambda. Are you going to use my biopsy for research? Are you going to do Visium or CosMX? I want to talk to you and the lab that wants my tissue about everything from experimental design to data analysis. I can help with the data analysis as well. I'd like to talk to the other patients in the study. They may be very pleased that they can help save lives." It must feel weird to be both subject and author, but this kind of thing has been in a keynote in the Bioconductor conference. My favorite keynote at the Bioconductor conference is usually the clinical one, the one about patients' stories (for example, see [Bioc2021](https://www.youtube.com/watch?v=OqZ44OqESlM) and [Bioc2020](https://www.youtube.com/watch?v=Ip8_AHqeBXM)), because without such stories, often I doubt if my research matters. It was said that doctors treating themselves or their families is frowned upon even when it's legal. But I'm not treating myself. Now I wonder if doctors call themselves doctors when seeing other doctors when they're sick.
