---
title: "From valley to valley, from foothill to foothill"
author: "Lambda Moses"
date: "2023-09-30"
categories: [cycling]
---

Captain's Log, stardate 101035.8, or Earth date June 9, 2023.

Long time no fondo, and I need to adapt to touring. Let me start---I mean restart---small, meaning the minimum distance of 100 km. Initially I planned this route to revisit the spot in Little T where some lupine colocalizes with sunflowers. However, lupine season is over (over at that spot but not yet in June in the Santa Monica mountains). Now it’s yucca and deer grass season instead. The vibrant green gave way to yellow and brown, but since not all vegetation was grass, most of some hills were green, from the chaparral.

<div class="strava-embed-placeholder" data-embed-type="activity" data-embed-id="9236129157"></div><script src="https://strava-embeds.com/embed.js"></script>

I couldn’t help but left kind of late. I really didn’t want to miss Jummah. I slept in because I stayed up booting Voyager's front tire whose side wall was partially compromised when I hit maybe a rock, so I was too late for the Toronto El-Tawhid jummah, the LGBTQ+ affirming mosque hosting services online. No I'm not gay---I'm asexual meaning I'm just not interested in dating and hence have never done so in the 28 years of my life---but I absolutely despise the sort of conservative hypocrisy, spewing the misogyny to signal piety while supporting Trump and fascist regimes that murder millions of Muslims. I'm pretty satisfied with our progressive niches. Then I went to the Usuli Institute Jummah online. The sermon was about 3 non-Muslim Australian journalists risking their lives and spending money to fly in eye witnesses from Afghanistan to prove that an award winning Australian soldier committed war crime, while most Muslims don't care and don't help. Well, I don't entirely agree, because I know many people who do care and do try to help, but it seems that those who care don't have the means while those with the means don't care. 

I kind of feel like the education system has failed me. Many of us are doctors and engineers, meaning we are well-educated. I grew up thinking that STEM major is cool. I though that my cool discoveries will save so many lives. However, as I get deeper into the field, I feel like I'm further and further away from saving lives, because I didn't know how fucked up our neoliberal healthcare system really is. It's much more business than healthcare. Changing the system will save way more lives than developing therapies. Plus the biomedical field is so specialized that I'm lightyears away from the clinic. It may take decades and millions of dollars for discoveries made with the help of R package Voyager and spatial -omics to get through the FDA and reach the patients. Even then, it's most likely so expensive that it's limited to the filthy rich, which means racial disparity in our day and age. Think of the exorbitant price of the very effective cystic fibrosis drugs, costing over $200,000 per course. We are trained to develop profitable tech, while intentionally left ignorant about how many people this horrible system kills. Which is why I'm thinking about getting into human geography after some spatial -omics postdocs, so I can apply my spatial data analysis skills to fight the system.

Anyway, so much for the rant. I went to the voyage to regain my gran fondo superpower. I'll write a blog post about my philosophy of the voyages later. I suppose that must be soon, before the formal beginning of my postdoc appointment (OK, I wrote the Captains Log right after the trip; now I'm well into my postdoc and STILL haven't written it). I think I should do another ride over 80 miles with lots of climbing, and some longer gravel rides, before tapering the few days before the tour (of Crystal Cove, Santa Catalina Island, Black Star Canyon, Chino Hills, Riverside, and Anaheim, which I just keep on delaying because I need to submit the paper about R package Voyager before I can let myself go).

To sort of boldly go somewhere Lambda has never gone before: I went into the neighborhoods in the Verdogos, in La Crescenta and Sunland. I have been to much of it last winter break after descending from Big T, but it was in the dark, so I revisited to take a better look. I have probably never gone to some parts of it before. I also revisited the Bolton Hall. I would like to go in there, and then climb the Haines Canyon gravel to Mt Lukens. But overall, it's not super interesting. Just the suburbs, a mini-downtown with shops, and many tributaries of the Verdugo Wash.

<iframe title="Pixelfed Post Embed" src="https://pixelfed.social/p/lambdamoses/613649622800579471/embed?caption=false&likes=false&layout=compact" class="pixelfed__embed" style="max-width: 100%; border: 0" width="400" allowfullscreen="allowfullscreen"></iframe><script async defer src="https://pixelfed.social/embed.js"></script>

Then getting to Little T. This is my 4th trip, but I still did stop for photos, as the flora has changed. Lots of super loud and smelly sports cars and motorcycles. Please, don't pollute our wonderful forest! Why destroy the very thing attracting you here? I really liked the EDM played in a white SUV at a turnout. I also saw a fox crossing the road when there were no cars. I think this is my first time seeing a fox in the wild. Meanwhile, was I the only woman in a few miles? Apparently all the motorcyclists and people talking outside cars were male. Is it safe? What if they take the chance to assault me so there aren't witnesses? I can't outrun them. Anyway, thank God everything was fine.

<iframe title="Pixelfed Post Embed" src="https://pixelfed.social/p/lambdamoses/613651122216250842/embed?caption=false&likes=false&layout=compact" class="pixelfed__embed" style="max-width: 100%; border: 0" width="400" allowfullscreen="allowfullscreen"></iframe><script async defer src="https://pixelfed.social/embed.js"></script>

I bombed down Little T fast, though stopped for a yucca photo. Then I headed to Hansen Dam to refill my water bottles. In March, I got to appreciate how this dam does flood control. Now it was pretty much back to normal, with the dirt trails revealed. The lake back in March turned into a lush oasis. I saw a wild rabbit when coming down the bike path from the dam.

<iframe title="Pixelfed Post Embed" src="https://pixelfed.social/p/lambdamoses/613652609292759178/embed?caption=false&likes=false&layout=compact" class="pixelfed__embed" style="max-width: 100%; border: 0" width="400" allowfullscreen="allowfullscreen"></iframe><script async defer src="https://pixelfed.social/embed.js"></script>

I was hungry. It shouldn't take long to get to Burbank. I climbed that closed road with a nice view of the Bob Hope airport I visited in January 2022; I descended back then. I think it was closed probably because of the Burbank landfill on this road. Anyway, I wasn't caught. The climb was hard. I haven't climbed something over 10% for so long for a while. There were two lads taking photos of their cool sports car at the gate at the top.

Again, Stough Canyon, another steep climb. I wanted to go there for the cool Tree of Life sculpture at the restroom. There was a large hiking group. A woman from the group asked me if the trail is hard. Honestly, having never been there, I don't know, but I would like to ride Wayfarer there. Though she thought it would be hard just because I said I need to ride a gravel bike there. The hardest hike is still easy compared to hard rides; by my standard, a hike is hard if the trail is so steep and rough that I have to scramble.

I bombed down the hill so fast that I overshot the turn. Then I headed to the Castaway wall, for the view at the parking lot. It was a bit too early for the DTLA lights to turn on, but I didn't want to wait for sunset as I didn't want to get home too late. There was a wedding at the restaurant.

<iframe title="Pixelfed Post Embed" src="https://pixelfed.social/p/lambdamoses/614021418381140109/embed?caption=false&likes=false&layout=compact" class="pixelfed__embed" style="max-width: 100%; border: 0" width="400" allowfullscreen="allowfullscreen"></iframe><script async defer src="https://pixelfed.social/embed.js"></script>

Nothing special in Kenneth Village. I did the detour to Occidental and Highland Park just to make it 100 km. Already hungry, and already past 8 pm so too late for me to cook after coming home, I had dinner at Wolfie's. There were two CS majors talking about C++ at the table next to me, probably Oxy students. The Oxy campus was lit up with lanterns in trees. I love the scholastic vibe of actually any college campus, as if there's some magic. Maybe it's not magic, because the college campus is one of the few places built for people rather than cars, even including campuses built after the rise of car culture, which includes the Caltech campus north of San Pasqual which was gradually built since the 1960s and the UCLA campus outside the core around Royce, Haines, Humanities, and Kerckhoff built after the 1950s. As a result, campuses have nice horticulture and art, to be appreciated at a walking speed. One more reason why cars suck.

I love Highland Park. If I go to USC Medical School for my next postdoc, then I might move to Highland Park if it's cheaper than Pasadena. I love Pasadena, but I'm sick of living so close to the freeway simply because I can't afford to live anywhere else and I don't want to deal with roommates. On Meridian, I passed by a really cool Latino (from the genre of music) neighborhood party. I'm glad that I scraped a little of the festivity.

Finally, to boldly go where I have never gone before, I went into some South Arroyo crannies, and greatly enjoyed the flower scent and solitude. Though I'm sure that it's not cheap. Whenever money comes into the picture, things get really ugly very quickly.
