project:
  type: website
  output-dir: docs

website:
  title: "These R the Voyages"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/lambdamoses
      - icon: mastodon
        href: https://fosstodon.org/@lambdamoses
format:
  html:
    theme: minty
    css: styles.css

editor: source

