project:
  type: website

website:
  title: "These R the Voyages"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/lambdamoses
      - icon: mastodon
        href: https://fosstodon.org/@lambdamoses
      - icon: twitter
        href: https://twitter.com/LambdaMoses
format:
  html:
    theme: cerulean
    css: styles.css

editor: visual

