---
title: "East Side Riders"
author: "Lambda Moses"
date: "2023-02-11"
draft: true
categories: [cycling]
---

"I probably can't make it," I said to myself, as I just snoozed for 20 minutes. Now I'm blessed with flexible work schedule, but if I keep on living this way, then I'll be doomed once I lose this flexibility after I graduate. I kept on getting up too late, until I need to yank myself out of bed to either conform to an earlier social schedule of events or maximize daylight time for a voyage. Because without [Frozen Turkey](https://getcoldturkey.com/features/), I often have trouble stopping what I'm doing, ending up staying up. Wilmington is kind of far from Pasadena. Taking into account traffic lights and the slow and chaotic part of DTLA, it would realistically take me about 1 and a half hours to ride hard and fast to cover the 21 miles to get to Wilmington, where this family friendly ride takes place. I only had less than 1:15 left. Anyway, if I still feel tired, then I'll go elsewhere, like re\_ grocery first and then Monrovia. Or worst case scenario, they leave without me, and I'll just continue on my own adventure, to check out some murals and interesting places on Central Ave that I blew past last time in CicLAvia last December. Or perhaps, just like the Tour de North Carson last March, I rode hard but still arrived 2 minutes late, only to find out that they wouldn't roll until half an hour later, so I had quite a bit of time to kill, talking to other riders.

<div class="strava-embed-placeholder" data-embed-type="activity" data-embed-id="8545943541"></div><script src="https://strava-embeds.com/embed.js"></script>

The slow part of DTLA began. My usual route through DTLA takes the N Spring St bike lane. The part of Spring St by the LA City Hall was closed, for an Iranian protest, presumably against the official celebration of the 44th anniversary of the Iranian "Islamic" Republic. The protest hadn't started yet. But Boo! Lots of Iranian Imperial flags. Maybe monarchists there. Death to monarchy, and death to all forms of authoritarianism! Anyway, I was running late. No time to take photos or to talk to people. While the road was closed, I could ride on the sidewalk, just more slowly. Meanwhile -- not to downplay the atrocities committed by the blasphemous Iranian government though I'm upset about the media double standard when it comes to human rights records of the US and its allies -- I wonder, on January 21, why couldn't we close the road when we protested against the [death of 312 people from traffic violence in LA City in 2022](https://www.streetsareforeveryone.org/blog/dying-on-the-streets-of-los-angeles), which was overshadowed by the Monterey Park shooting that night in the news? Why couldn't we close the road to protest against climate suicide as the car and fossil fuel industries resist climate action? Even many progressives don't question car culture.

